// You are given two strings s and t.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Return the letter that was added to t.
//
//
//
// Example 1:
//
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:
//
// Input: s = "", t = "y"
// Output: "y"
// Example 3:
//
// Input: s = "a", t = "aa"
// Output: "a"
// Example 4:
//
// Input: s = "ae", t = "aea"
// Output: "a"
//
//
// Constraints:
//
// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lower-case English letters.





class Solution {
    public char findTheDifference(String s, String t) {
        int[] vals = new int[26];
        int n = s.length();
        for(int i = 0; i < n; i++){
            vals[s.charAt(i) - 'a']++;
            vals[t.charAt(i) - 'a']--;
        }
        vals[t.charAt(n) - 'a']--;
        int i = 0;
        for(;i < vals.length; i++){
            if(vals[i] != 0){
                break;
            }
        }
        return (char) (i + 'a');
    }
}
// Time : O(N)
// Space : O(N)





class Solution {
    public char findTheDifference(String s, String t) {
        int x = 0;
        int n = s.length();
        for(int i = 0; i < n; i++){
            x ^= s.charAt(i);
            x ^= t.charAt(i);
        }
        x ^= t.charAt(n);
        return (char) x;
    }
}
// Time : O(N)
// Space : O(1)
